Repository openforge/OPENFORGE.IO, pull requests merged in 2020-01, with the labels that each got.

#415 feat(navbar): update styles to match new design
  src/assets/i18n/en.ts
  src/components/app-nav-header/app-nav-header.scss
  src/components/app-nav-header/app-nav-header.tsx
  src/pages/open-forge-app/open-forge-app.tsx
Labels: QA Passes

#414 feat(contact): added new design
  src/assets/contact/bell-graphic.png
  src/assets/contact/bell-graphic.webp
  src/assets/contact/contact-graphic.png
  src/assets/contact/contact-graphic.webp
  src/assets/contact/letter-background.png
  src/assets/contact/letter-background.webp
  src/assets/contact/mailbox-graphic.png
  src/assets/contact/mailbox-graphic.webp
  src/assets/contact/map-graphic.png
  src/assets/contact/map-graphic.webp
  src/assets/i18n/en.ts
  src/assets/svg/contact-anim.svg
  src/components/app-input/app-input.scss
  src/components/app-input/app-input.tsx
  src/pages/app-contact/app-contact.scss
  src/pages/app-contact/app-contact.tsx
Labels: QA Passes

#411 Feat/home
  src/assets/apps/mobilemeasures/graphic-example-1.png
  src/assets/apps/mobilemeasures/graphic-example-2.png
  src/assets/apps/mobilemeasures/graphic-example-3.png
  src/assets/home-graphic-mobilemeasures-pattern.jpg
  src/assets/home-graphic-vanlife-pattern.jpg
  src/assets/home-graphic-vanlife-pattern.webp
  src/assets/i18n/en.ts
  src/assets/svg/home-animation-desktop.svg
  src/assets/svg/home-animation-mobile.svg
  src/components/app-blog-featured-home/app-blog-featured-home.scss
  src/components/app-blog-featured-home/app-blog-featured-home.spec.ts
  src/components/app-blog-featured-home/app-blog-featured-home.tsx
  src/components/app-blog-featured-home/readme.md
  src/components/app-cta/app-cta.scss
  src/components/app-cta/app-cta.tsx
  src/components/app-footer/app-footer.scss
  src/components/app-footer/app-footer.tsx
  src/pages/app-home/app-home.scss
  src/pages/app-home/app-home.tsx
  src/pages/open-forge-app/open-forge-app.tsx
  src/shared/fetch-handler.ts
Labels: QA Passes

#410 fix: check current location to set active class
  src/pages/open-forge-app/open-forge-app.tsx
Labels: Needs Code Review, QA Passes

#420 Feat/partners
  src/assets/i18n/en.ts
  src/assets/partners-1776-logo.png
  src/assets/partners-215-logo.png
  src/assets/partners-drexel-logo.png
  src/assets/partners-financial-gps-logo.png
  src/assets/partners-ionic-logo-landscape.png
  src/assets/partners-strapi-logo.png
  src/assets/svg/partners-graphic-cta.svg
  src/assets/svg/partners-graphic-header.svg
  src/pages/app-partners/app-partners.scss
  src/pages/app-partners/app-partners.tsx
  src/pages/open-forge-app/open-forge-app.tsx
Labels: QA Passes

#412 Feat/search
  src/components/app-nav-header/app-nav-header.tsx
  src/components/app-search-results/app-search-results.scss
  src/components/app-search-results/app-search-results.spec.ts
  src/components/app-search-results/app-search-results.tsx
  src/components/app-search-results/readme.md
Labels: QA Passes

#405 feat: add budget file
  budget.json
Labels: QA Passes

#397 Fix/cta size
  src/components/app-cta/app-cta.scss
  src/components/app-cta/app-cta.tsx
  src/styles/_variables.scss
Labels: Dev Passes, QA Passes

#436 fix(footer): hide press kit link
  src/components/app-footer/app-footer.tsx
Labels: QA Passes

#435 fix(navbar): hide links
  src/components/app-nav-header/app-nav-header.tsx
Labels: QA Passes

#434 fix(home): project typo
  src/assets/i18n/en.ts
Labels: QA Passes

#437 fix(home): hide learn more button
  src/pages/app-home/app-home.tsx
Labels: QA Passes

#438 fix(partners): remove scroll
  src/pages/app-partners/app-partners.scss
Labels: QA Passes

#439 Fix/blog footer
  src/pages/app-blog/app-blog.tsx
Labels: QA Passes

#433 fix(): hide matt
  src/components/app-members-section/app-members-section.tsx
  src/components/app-members/app-members.tsx
Labels: QA Passes

#431 feature(): replace google tag manager tags per 215 recommendations
  src/index.html
Labels: Priority: High, QA Passes

#419 feat(opportunities): start the new design for the opportunities
  src/assets/i18n/en.ts
  src/assets/opportunities/codemaster.png
  src/assets/opportunities/designmaster.png
  src/assets/opportunities/opportunities-arrow-animated.svg
  src/assets/opportunities/opportunities-arrow.svg
  src/assets/opportunities/opportunities-design-active.svg
  src/assets/opportunities/opportunities-designer-candidate.svg
  src/assets/opportunities/opportunities-dev-active.svg
  src/assets/opportunities/opportunities-dev-candidate.svg
  src/assets/opportunities/opportunities-header-animated.svg
  src/assets/opportunities/opportunities-header.svg
  src/assets/opportunities/opportunities-mobile-design-active.svg
  src/assets/opportunities/opportunities-mobile-dev-active.svg
  src/assets/opportunities/opportunities-mobile-header-animated.svg
  src/assets/opportunities/opportunities-mobile-transition-design-dev.svg
  src/assets/opportunities/opportunities-mobile-transition-design.svg
  src/assets/opportunities/opportunities-mobile-transition-dev-design.svg
  src/assets/opportunities/opportunities-mobile-transition-dev.svg
  src/assets/opportunities/opportunities-tablet-design-active.svg
  src/assets/opportunities/opportunities-tablet-dev-active.svg
  src/assets/opportunities/opportunities-tablet-header-animated.svg
  src/assets/opportunities/opportunities-tablet-transition-design-dev.svg
  src/assets/opportunities/opportunities-tablet-transition-design.svg
  src/assets/opportunities/opportunities-tablet-transition-dev-design.svg
  src/assets/opportunities/opportunities-tablet-transition-dev.svg
  src/assets/opportunities/opportunities-transition-design-dev.svg
  src/assets/opportunities/opportunities-transition-design.svg
  src/assets/opportunities/opportunities-transition-dev-design.svg
  src/assets/opportunities/opportunities-transition-dev.svg
  src/assets/opportunities/test-designer.png
  src/assets/opportunities/test-dev.png
  src/components/app-input/app-input.scss
  src/components/app-input/app-input.tsx
  src/components/content-graphic/content-graphic.scss
  src/components/content-graphic/content-graphic.tsx
  src/pages/app-opportunities/app-opportunities.scss
  src/pages/app-opportunities/app-opportunities.tsx
  src/pages/open-forge-app/open-forge-app.tsx
Labels: QA Passes

#442 Fix/dropdown styles
  src/components/app-nav-header/app-nav-header.scss
  src/components/app-nav-header/app-nav-header.tsx
  src/pages/open-forge-app/open-forge-app.tsx
Labels: QA Passes

#440 fix(cta): cta styles
  src/components/app-cta/app-cta.scss
  src/components/app-cta/app-cta.tsx
  src/pages/app-about/app-about.scss
  src/pages/app-about/app-about.tsx
  src/pages/app-partners/app-partners.scss
Labels: QA Passes

#455 fix(our work): space on right
  src/pages/app-our-work-single/app-our-work-single.scss
Labels: Dev Passes, QA Passes

#454 fix(opportunities): update header styles on mobile
  src/pages/app-opportunities/app-opportunities.scss
Labels: Dev Passes, QA Passes

#453 fix(partners): fix carousel scroll
  src/pages/app-partners/app-partners.scss
Labels: Dev Passes, QA Passes

#452 fix(partners): update styles to center carousel
  src/pages/app-partners/app-partners.scss
Labels: Dev Passes, QA Passes

#446 fix(footer): hide forge button
  src/components/app-footer/app-footer.tsx
Labels: Dev Passes, QA Passes

#445 fix(contact): remvoe asterisk from phone
  src/assets/i18n/en.ts
  src/pages/app-contact/app-contact.tsx
Labels: Dev Passes, QA Passes

#444 fix(our work): header on tablet
  src/pages/app-our-work/app-our-work.scss
Labels: Dev Passes, QA Passes

#451 fix(about): active and hover styles
  src/pages/app-about/app-about.scss
Labels: Dev Passes, QA Passes

#443 fix(our work): small screens
  src/pages/app-our-work/app-our-work.scss
Labels: Dev Passes, QA Passes

#430 fix(): fix redirect twitter
  src/components/app-blog-card/app-blog-card.tsx
  src/components/app-blog-content/app-blog-content.tsx
  src/components/app-blog-featured-home/app-blog-featured-home.tsx
  src/components/app-blog-featured/app-blog-featured.tsx
  src/components/app-members-section/app-members-section.tsx
  src/pages/app-team-landing/app-team-landing.tsx
Labels: Dev Passes, QA Passes

#456 fix(home): remove white space on tablet
  src/pages/app-home/app-home.scss
Labels: Dev Passes

#458 Fix/font styles mobile
  src/assets/fonts/Roboto.css
  src/components/app-search-results/app-search-results.scss
  src/pages/app-detailed-service/app-detailed-service.scss
  src/pages/app-partners/app-partners.scss
Labels: QA Passes

#459 fix(app-footer): add target=_blank for email opening
  src/components/app-footer/app-footer.tsx
Labels: QA Passes

#465 fix(app-team-landing): add restraint for querySelector for resize
  src/pages/app-team-landing/app-team-landing.tsx
Labels: QA Passes

#464 fix(app-opportunities): update mobile height of header
  src/pages/app-opportunities/app-opportunities.scss
Labels: QA Ready

#476 fix(footer): add accessibility links aria label
  src/components/app-footer/app-footer.tsx
Labels: QA Passes

#477 fix(): accessibility ids
  src/components/app-blog-featured-home/app-blog-featured-home.tsx
Labels: resolved

#480 fix(): update bootstrap and jquery to avoid vulnerabilities
  src/index.html
Labels: QA Passes

#478 fix(): perf images
  src/components/app-blog-card/app-blog-card.scss
  src/components/app-blog-card/app-blog-card.tsx
  src/components/app-blog-content/app-blog-content.scss
  src/components/app-blog-content/app-blog-content.tsx
  src/components/app-blog-featured-home/app-blog-featured-home.scss
  src/components/app-blog-featured-home/app-blog-featured-home.tsx
  src/components/app-blog-featured/app-blog-featured.scss
  src/components/app-blog-featured/app-blog-featured.tsx
  src/pages/app-blog-post/app-blog-post.tsx
  src/pages/app-home/app-home.scss
  src/pages/app-home/app-home.tsx
  src/pages/app-our-work-single/app-our-work-single.scss
  src/pages/app-our-work-single/app-our-work-single.tsx
  src/pages/app-our-work/app-our-work.scss
  src/pages/app-our-work/app-our-work.tsx
  src/pages/app-partners/app-partners.tsx
Labels: QA Passes

#474 fix(our work): our work store buttons
  src/pages/app-our-work-single/app-our-work-single.scss
Labels: QA Passes

#475 fix(navbar): our work active state
  src/components/app-nav-header/app-nav-header.tsx
  src/pages/app-our-work-single/app-our-work-single.tsx
  src/pages/app-our-work/app-our-work.tsx
  src/pages/open-forge-app/open-forge-app.tsx
Labels: QA Passes

#481 Feat/sw reload
  functions/package.json
  package-lock.json
  src/pages/open-forge-app/open-forge-app.tsx
  stencil.config.ts
Labels: QA Passes
